---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

env:
  - CAP_BROWSER="firefox" CAP_VERSION="42.0" CAP_PLATFORM="Windows 10"
  - CAP_BROWSER="chrome" CAP_VERSION="46.0" CAP_PLATFORM="Windows 10"
  - CAP_BROWSER="safari" CAP_VERSION="9.0" CAP_PLATFORM="OS X 10.11"
  - CAP_BROWSER="MicrosoftEdge" CAP_VERSION="20.10240" CAP_PLATFORM="Windows 10"
  - CAP_BROWSER="internet explorer" CAP_VERSION="11.0" CAP_PLATFORM="Windows 10"

#  allow_failures:
#    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test
  - sh run-webdriver.sh
